version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "8001:8000"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared
    depends_on:
      - backend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
      - model
    volumes:
      - shared-data:/usr/share/nginx/html/shared

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
